# Generated by Django 2.0.1 on 2018-01-21 19:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Askstories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('by', models.CharField(max_length=100)),
                ('deleted', models.NullBooleanField()),
                ('text', models.TextField(null=True)),
                ('dead', models.NullBooleanField()),
                ('parent', models.CharField(max_length=100)),
                ('descendants', models.IntegerField(null=True)),
                ('kids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('score', models.IntegerField(null=True)),
                ('time', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200, null=True)),
                ('parts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('poll', models.IntegerField(null=True)),
            ],
        ),
    ]
